# Generated by Django 5.2.12 on 2026-03-28 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("regions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("inis", "ИНИС"),
                            ("isna", "ИСНА"),
                            ("dgd", "Данные ДГД"),
                            ("appeals", "Обжалования"),
                        ],
                        max_length=20,
                        verbose_name="источник",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидание"),
                            ("running", "Выполняется"),
                            ("done", "Завершено"),
                            ("error", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="начало"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="завершение"
                    ),
                ),
                (
                    "records_total",
                    models.IntegerField(default=0, verbose_name="записей всего"),
                ),
                (
                    "records_imported",
                    models.IntegerField(
                        default=0, verbose_name="записей импортировано"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="сообщение об ошибке"),
                ),
                (
                    "params",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="параметры"
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="запустил",
                    ),
                ),
            ],
            options={
                "verbose_name": "задача импорта",
                "verbose_name_plural": "задачи импорта",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CompletedInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("inis", "ИНИС"), ("isna", "ИСНА")],
                        max_length=10,
                        verbose_name="источник",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(max_length=100, verbose_name="ID в источнике"),
                ),
                (
                    "management",
                    models.CharField(
                        help_text="УНА / УКН / УНН / УДМ / УАКН / ...",
                        max_length=20,
                        verbose_name="управление",
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        help_text="ДФНО / обычная / ...",
                        max_length=50,
                        verbose_name="тип проверки",
                    ),
                ),
                ("completed_date", models.DateField(verbose_name="дата завершения")),
                (
                    "amount_assessed",
                    models.BigIntegerField(
                        default=0, verbose_name="доначислено (тенге)"
                    ),
                ),
                (
                    "amount_collected",
                    models.BigIntegerField(default=0, verbose_name="взыскано (тенге)"),
                ),
                (
                    "is_counted",
                    models.BooleanField(
                        default=False, verbose_name="учитывается (KPI 3)"
                    ),
                ),
                (
                    "is_accepted",
                    models.BooleanField(
                        default=False, verbose_name="принято (KPI 1, 2)"
                    ),
                ),
                (
                    "is_anomaly",
                    models.BooleanField(default=False, verbose_name="аномалия"),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="исходные данные"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completed_inspections",
                        to="regions.region",
                        verbose_name="регион",
                    ),
                ),
                (
                    "import_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_inspections",
                        to="etl.importjob",
                        verbose_name="задача импорта",
                    ),
                ),
            ],
            options={
                "verbose_name": "завершённая проверка",
                "verbose_name_plural": "завершённые проверки",
                "indexes": [
                    models.Index(
                        fields=["region", "management", "completed_date"],
                        name="ci_region_mgmt_date_idx",
                    ),
                    models.Index(
                        fields=["is_counted", "is_accepted"], name="ci_flags_idx"
                    ),
                ],
                "unique_together": {("source", "source_id")},
            },
        ),
        migrations.CreateModel(
            name="AppealDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ID в источнике"
                    ),
                ),
                (
                    "amount_cancelled",
                    models.BigIntegerField(
                        default=0, verbose_name="отменённая сумма (тенге)"
                    ),
                ),
                (
                    "is_counted",
                    models.BooleanField(default=False, verbose_name="учитывается"),
                ),
                (
                    "completion_date",
                    models.DateField(verbose_name="дата завершения акта"),
                ),
                (
                    "decision_date",
                    models.DateField(
                        verbose_name="дата решения Апелляционной комиссии"
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="исходные данные"
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appeal_decisions",
                        to="regions.region",
                        verbose_name="регион",
                    ),
                ),
                (
                    "import_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appeal_decisions",
                        to="etl.importjob",
                        verbose_name="задача импорта",
                    ),
                ),
            ],
            options={
                "verbose_name": "решение по обжалованию",
                "verbose_name_plural": "решения по обжалованиям",
                "indexes": [
                    models.Index(
                        fields=["region", "decision_date"],
                        name="ad_region_decision_idx",
                    ),
                    models.Index(fields=["is_counted"], name="ad_counted_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ActiveInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=10, verbose_name="источник")),
                (
                    "source_id",
                    models.CharField(max_length=100, verbose_name="ID в источнике"),
                ),
                (
                    "management",
                    models.CharField(max_length=20, verbose_name="управление"),
                ),
                (
                    "case_type",
                    models.CharField(
                        help_text="Исключить: уголовные дела, запросы правоохранит. органов",
                        max_length=50,
                        verbose_name="тип дела",
                    ),
                ),
                (
                    "prescription_date",
                    models.DateField(verbose_name="дата вручения предписания"),
                ),
                (
                    "is_counted",
                    models.BooleanField(default=False, verbose_name="учитывается"),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="исходные данные"
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="active_inspections",
                        to="regions.region",
                        verbose_name="регион",
                    ),
                ),
                (
                    "import_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_inspections",
                        to="etl.importjob",
                        verbose_name="задача импорта",
                    ),
                ),
            ],
            options={
                "verbose_name": "проводимая проверка",
                "verbose_name_plural": "проводимые проверки",
                "indexes": [
                    models.Index(
                        fields=["region", "prescription_date"],
                        name="ai_region_date_idx",
                    ),
                    models.Index(fields=["is_counted"], name="ai_counted_idx"),
                ],
                "unique_together": {("source", "source_id")},
            },
        ),
        migrations.CreateModel(
            name="ManualInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="год")),
                (
                    "kbk_share_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Используется для KPI 1 и KPI 2",
                        max_digits=8,
                        null=True,
                        verbose_name="доля по КБК (%)",
                    ),
                ),
                (
                    "staff_count",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Используется для KPI 4",
                        null=True,
                        verbose_name="кол-во сотрудников",
                    ),
                ),
                (
                    "entered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="дата ввода"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="примечания")),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manual_inputs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="внёс",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manual_inputs",
                        to="regions.region",
                        verbose_name="регион",
                    ),
                ),
            ],
            options={
                "verbose_name": "ручной ввод",
                "verbose_name_plural": "ручные вводы",
                "ordering": ["-year", "region__order"],
                "unique_together": {("region", "year")},
            },
        ),
    ]
