# Generated by Django 5.2.12 on 2026-03-28 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("regions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KPIFormula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kpi_type",
                    models.CharField(
                        choices=[
                            ("assessment", "KPI 1 — Доначисление"),
                            ("collection", "KPI 2 — Взыскание"),
                            ("avg_assessment", "KPI 3 — Среднее доначисление"),
                            ("workload", "KPI 4 — Занятость"),
                            ("long_inspections", "KPI 5 — Проверки > 6 мес."),
                            ("cancelled", "KPI 6 — Отменённые суммы"),
                        ],
                        max_length=30,
                        verbose_name="тип KPI",
                    ),
                ),
                ("version", models.PositiveSmallIntegerField(verbose_name="версия")),
                (
                    "config",
                    models.JSONField(
                        help_text="Пороги баллов и параметры расчёта",
                        verbose_name="конфигурация",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="примечания")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kpi_formulas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="создал",
                    ),
                ),
            ],
            options={
                "verbose_name": "формула KPI",
                "verbose_name_plural": "формулы KPI",
                "ordering": ["kpi_type", "-version"],
                "unique_together": {("kpi_type", "version")},
            },
        ),
        migrations.CreateModel(
            name="KPIResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kpi_type",
                    models.CharField(
                        choices=[
                            ("assessment", "KPI 1 — Доначисление"),
                            ("collection", "KPI 2 — Взыскание"),
                            ("avg_assessment", "KPI 3 — Среднее доначисление"),
                            ("workload", "KPI 4 — Занятость"),
                            ("long_inspections", "KPI 5 — Проверки > 6 мес."),
                            ("cancelled", "KPI 6 — Отменённые суммы"),
                        ],
                        max_length=30,
                        verbose_name="тип KPI",
                    ),
                ),
                ("date_from", models.DateField(verbose_name="период с")),
                ("date_to", models.DateField(verbose_name="период по")),
                (
                    "plan",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                        verbose_name="план",
                    ),
                ),
                (
                    "fact",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                        verbose_name="факт",
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="исполнение (%)",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(default=0, verbose_name="баллы"),
                ),
                (
                    "calc_details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="детали расчёта"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("submitted", "На утверждении"),
                            ("approved", "Утверждён"),
                            ("rejected", "Возвращён"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата расчёта"
                    ),
                ),
                (
                    "calculated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calculated_kpis",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="рассчитал",
                    ),
                ),
                (
                    "formula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="kpi.kpiformula",
                        verbose_name="формула",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kpi_results",
                        to="regions.region",
                        verbose_name="регион",
                    ),
                ),
            ],
            options={
                "verbose_name": "результат KPI",
                "verbose_name_plural": "результаты KPI",
                "ordering": ["region__order", "kpi_type"],
                "indexes": [
                    models.Index(
                        fields=["region", "date_from", "date_to"],
                        name="kr_region_period_idx",
                    ),
                    models.Index(fields=["status"], name="kr_status_idx"),
                ],
                "unique_together": {
                    ("region", "kpi_type", "date_from", "date_to", "formula")
                },
            },
        ),
        migrations.CreateModel(
            name="KPISummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField(verbose_name="период с")),
                ("date_to", models.DateField(verbose_name="период по")),
                (
                    "score_assessment",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="KPI 1 баллы"
                    ),
                ),
                (
                    "score_collection",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="KPI 2 баллы"
                    ),
                ),
                (
                    "score_avg_assessment",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="KPI 3 баллы"
                    ),
                ),
                (
                    "score_workload",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="KPI 4 баллы"
                    ),
                ),
                (
                    "score_long_inspections",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="KPI 5 баллы"
                    ),
                ),
                (
                    "score_cancelled",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="KPI 6 баллы"
                    ),
                ),
                (
                    "score_total",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="итого баллов"
                    ),
                ),
                (
                    "rank",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="позиция"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("submitted", "На утверждении"),
                            ("approved", "Утверждён"),
                            ("rejected", "Возвращён"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата расчёта"
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kpi_summaries",
                        to="regions.region",
                        verbose_name="регион",
                    ),
                ),
            ],
            options={
                "verbose_name": "итог KPI",
                "verbose_name_plural": "итоги KPI",
                "ordering": ["rank", "region__order"],
                "unique_together": {("region", "date_from", "date_to")},
            },
        ),
    ]
