# Generated by Django 5.2.12 on 2026-03-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Код ДГД, например: 06xx, 62xx",
                        max_length=4,
                        unique=True,
                        verbose_name="код",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=100, verbose_name="название (рус.)"),
                ),
                (
                    "name_kz",
                    models.CharField(max_length=100, verbose_name="атауы (қаз.)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="name (eng.)"),
                ),
                (
                    "is_summary",
                    models.BooleanField(
                        default=False,
                        help_text="True для КГД (итого по РК) — не участвует в рейтинге",
                        verbose_name="сводный",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="порядок сортировки"
                    ),
                ),
            ],
            options={
                "verbose_name": "регион / ДГД",
                "verbose_name_plural": "регионы / ДГД",
                "ordering": ["order"],
            },
        ),
    ]
