# Generated by Django 5.2.12 on 2026-03-28 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("kpi", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submit", "Отправлено на утверждение"),
                            ("approve", "Утверждено"),
                            ("reject", "Возвращено на доработку"),
                            ("recalc", "Запрос пересчёта"),
                        ],
                        max_length=20,
                        verbose_name="действие",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата действия"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор действия",
                    ),
                ),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="kpi.kpisummary",
                        verbose_name="итог KPI",
                    ),
                ),
            ],
            options={
                "verbose_name": "действие по отчёту",
                "verbose_name_plural": "история утверждений",
                "ordering": ["created_at"],
            },
        ),
    ]
